name: Análisis de SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # 2. Configurar JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # 3. Instalar dependencias (si usas Maven)
      - name: Instalar dependencias
        run: mvn clean install

      # 4. Ejecutar análisis con SonarQube
      - name: Ejecutar análisis con SonarQube
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=mi-proyecto \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 5. Subir el reporte de SonarQube como artefacto
      - name: Subir reporte de SonarQube como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: sonar-report
          path: target/sonar/report-task.txt



